---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: exporter-mongodb
  name: exporter-mongodb
  namespace: easytravel-nonprod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: exporter-mongodb
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: exporter-mongodb
      annotations:
         metrics.dynatrace.com/scrape: 'true'
         metrics.dynatrace.com/port: '9121'
         metrics.dynatrace.com/secure: 'false'
    spec:
      containers:
      - env:
        - name: MONGODB_URI
          value: mongodb://etAdmin:adminadmin@easytravel-mongodb-service:27017/admin?ssl=true
        image: percona/mongodb_exporter:0.32
        name: exporter-mongodb
        ports:
        - containerPort: 9121
