---
apiVersion: v1
kind: Service
metadata:
  labels:
    easytravel-tier: easytravel-configuration-service
  name: easytravel-configuration-service
  namespace: easytravel-prod
spec:
  externalTrafficPolicy: Cluster
  ports:
  - protocol: TCP
    targetPort: 8080
    port: 8080
  selector:
    easytravel-tier: easytravel-backend
  sessionAffinity: None
  type: LoadBalancer
