---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    easytravel-tier: easytravel-mongodb
  name: easytravel-mongodb
  namespace: easytravel-prod
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      easytravel-tier: easytravel-mongodb
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        easytravel-tier: easytravel-mongodb
        version: 2.0.0.3156
      labels:
        easytravel-tier: easytravel-mongodb
        tier: database
        app.kubernetes.io/name: easytravel-mongodb
        app.kubernetes.io/part-of: easytravel
        app.kubernetes.io/version: 2.0.0.3156
    spec:
      nodeSelector:
        group: small
      containers:
      - env:
        - name: DT_RELEASE_VERSION
          value: 2.0.0.3156
        - name: DT_RELEASE_BUILD_VERSION
          value: 2.0.0.3156
        - name: DT_RELEASE_STAGE
          value: easytravel-prod
        - name: DT_RELEASE_PRODUCT
          value: easytravel
        image: dynatrace/easytravel-mongodb:2.0.0.3156
        name: easytravel-mongodb
        ports:
        - containerPort: 27017
          protocol: TCP
        - containerPort: 28017
          protocol: TCP
        resources:
          requests:
            memory: "500Mi"
          limits:
            memory: "500Mi"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    easytravel-tier: easytravel-mongodb
  name: easytravel-mongodb-service
  namespace: easytravel-prod
spec:
  ports:
  - name: "27017"
    port: 27017
    protocol: TCP
    targetPort: 27017
  - name: "28017"
    port: 28017
    protocol: TCP
    targetPort: 28017
  selector:
    easytravel-tier: easytravel-mongodb
  sessionAffinity: None
  type: ClusterIP
