---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    easytravel-tier: easytravel-mongodb
  name: easytravel-mongodb
  namespace: easytravel-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      easytravel-tier: easytravel-mongodb
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        easytravel-tier: easytravel-mongodb
        version: 2.0.0.3156
      labels:
        easytravel-tier: easytravel-mongodb
        tier: database
        app.kubernetes.io/name: easytravel-mongodb
        app.kubernetes.io/part-of: easytravel
        app.kubernetes.io/version: 2.0.0.3156
    spec:
      containers:
      - image: dynatrace/easytravel-mongodb:2.0.0.3156
        name: easytravel-mongodb
        ports:
        - containerPort: 27017
          protocol: TCP
        - containerPort: 28017
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    easytravel-tier: easytravel-mongodb
  name: easytravel-mongodb-service
  namespace: easytravel-prod
spec:
  ports:
  - name: "27017"
    port: 27017
    protocol: TCP
    targetPort: 27017
  - name: "28017"
    port: 28017
    protocol: TCP
    targetPort: 28017
  selector:
    easytravel-tier: easytravel-mongodb
  sessionAffinity: None
  type: ClusterIP
