---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    easytravel-tier: easytravel-nginx
  name: easytravel-nginx
  namespace: easytravel-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      easytravel-tier: easytravel-nginx
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        version: 2.0.0.3256
      labels:
        easytravel-tier: easytravel-nginx
        tier: nginx
        team: easytravel-devops
        app.kubernetes.io/name: easytravel-nginx
        app.kubernetes.io/part-of: easytravel
        app.kubernetes.io/version: 2.0.0.3256
      name: easytravel-nginx
    spec:
      containers:
      - env:
        - name: ET_FRONTEND_LOCATION
          value: easytravel-frontend-service:8080
        image: dynatrace/easytravel-nginx:2.0.0.3256
        imagePullPolicy: Always
        name: easytravel-nginx
        ports:
        - containerPort: 80
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    easytravel-tier: easytravel-nginx-service
  name: easytravel-prod-nginx-service
  namespace: easytravel-prod
spec:
  externalTrafficPolicy: Cluster
  ports:
  - protocol: TCP
    targetPort: 80
    port: 80
  selector:
    easytravel-tier: easytravel-nginx
  sessionAffinity: None
  type: LoadBalancer
