---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    easytravel-tier: easytravel-frontend
  name: easytravel-frontend
  namespace: easytravel-nonprod
spec:
  replicas: 1
  selector:
    matchLabels:
      easytravel-tier: easytravel-frontend
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        version: 2.0.0.3256
      labels:
        easytravel-tier: easytravel-frontend
        tier: frontend
        team: easytravel-devops
        app.kubernetes.io/name: easytravel-frontend
        app.kubernetes.io/part-of: easytravel
        app.kubernetes.io/version: 2.0.0.3256
    spec:
      containers:
      - env:
        - name: ET_FRONTEND_LOCATION
          value: easytravel-frontend-service:8080
        - name: DT_RELEASE_VERSION
          value: 2.0.0.3256
        - name: DT_RELEASE_STAGE
          value: easytravel-nonprod
        - name: DT_RELEASE_PRODUCT
          value: easytravel
        - name: ET_BACKEND_URL
          value: http://easytravel-backend-service:8080
        - name: JAVA_OPTS
          value: -Xms256m -Xmx512m
        image: dynatrace/easytravel-frontend:2.0.0.3256
        imagePullPolicy: Always
        name: easytravel-frontend
        ports:
        - containerPort: 8080
          protocol: TCP
        - containerPort: 8280
          protocol: TCP
        resources:
          requests:
            memory: "700Mi"
          limits:
            memory: "700Mi"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    easytravel-tier: easytravel-frontend
  name: easytravel-frontend-service
  namespace: easytravel-nonprod
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: port1
    nodePort: 30080
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: port2
    nodePort: 30280
    port: 8280
    protocol: TCP
    targetPort: 8280
  selector:
    easytravel-tier: easytravel-frontend
  sessionAffinity: None
  type: NodePort
