---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    easytravel-tier: easytravel-backend
  name: easytravel-backend
  namespace: easytravel-nonprod
spec:
  replicas: 2
  selector:
    matchLabels:
      easytravel-tier: easytravel-backend
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        easytravel-tier: easytravel-backend
        tier: backend
      name: easytravel-backend
    spec:
      containers:
      - env:
        - name: ET_DATABASE_LOCATION
          value: easytravel-mongodb-service:27017
        - name: JAVA_OPTS
          value: -Xms256m -Xmx512m
        image: dynatrace/easytravel-backend:2.0.0.3256
        imagePullPolicy: Always
        name: easytravel-backend
        ports:
        - containerPort: 8009
          protocol: TCP
        - containerPort: 8005
          protocol: TCP
        - containerPort: 8080
          protocol: TCP
        resources:
          requests:
            memory: "1024Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    easytravel-tier: easytravel-backend-service
  name: easytravel-backend-service
  namespace: easytravel-nonprod
spec:
  ports:
  - name: port5
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: port3
    port: 8009
    protocol: TCP
    targetPort: 8009
  - name: port4
    port: 8005
    protocol: TCP
    targetPort: 8005
  selector:
    easytravel-tier: easytravel-backend
  sessionAffinity: None
  type: ClusterIP
