---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    easytravel-tier: easytravel-backend
  name: easytravel-backend
  namespace: easytravel-nonprod
spec:
  replicas: 1
  selector:
    matchLabels:
      easytravel-tier: easytravel-backend
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      annotations:
        version: 2.0.0.3256
      labels:
        easytravel-tier: easytravel-backend
        tier: backend
        team: easytravel-devops
        app.kubernetes.io/name: easytravel-backend
        app.kubernetes.io/part-of: easytravel
        app.kubernetes.io/version: 2.0.0.3256
      name: easytravel-backend
    spec:
      containers:
      - env:
        - name: ET_FRONTEND_LOCATION
          value: easytravel-frontend-service:8080
        - name: DT_RELEASE_VERSION
          value: 2.0.0.3256
        - name: DT_RELEASE_STAGE
          value: easytravel-nonprod
        - name: DT_RELEASE_PRODUCT
          value: easytravel
        - name: ET_DATABASE_LOCATION
          value: easytravel-mongodb-service:27017
        - name: JAVA_OPTS
          value: -Xms256m -Xmx512m
        image: dynatrace/easytravel-backend:2.0.0.3256
        imagePullPolicy: Always
        name: easytravel-backend
        ports:
        - containerPort: 8009
          protocol: TCP
        - containerPort: 8005
          protocol: TCP
        - containerPort: 8080
          protocol: TCP
        resources:
          requests:
            memory: "700Mi"
          limits:
            memory: "700Mi"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    easytravel-tier: easytravel-backend-service
  name: easytravel-backend-service
  namespace: easytravel-nonprod
spec:
  ports:
  - name: port5
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: port3
    port: 8009
    protocol: TCP
    targetPort: 8009
  - name: port4
    port: 8005
    protocol: TCP
    targetPort: 8005
  selector:
    easytravel-tier: easytravel-backend
  sessionAffinity: None
  type: ClusterIP
