---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: loadgenerator
  name: loadgenerator
  namespace: easytravel-nonprod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loadgenerator
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: loadgenerator
    spec:
      containers:
      - env:
        - name: ET_FRONTEND_URL
          value: http://easytravel-nonprod-nginx-service:80
        - name: ET_BACKEND_URL
          value: http://easytravel-backend-service:8080
        - name: ET_PROBLEMS
          value: DatabaseCleanup
        image: dynatrace/easytravel-loadgen:latest
        name: easytravel-loadgen
        resources:
          requests:
            memory: "500Mi"
          limits:
            memory: "500Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: angular-loadgenerator
  name: angular-loadgenerator
  namespace: easytravel-nonprod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: angular-loadgenerator
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: angular-loadgenerator
    spec:
      containers:
      - env:
        - name: ET_ANGULAR_FRONTEND_URL
          value: http://easytravel-nonprod-angular-nginx-service:80
        - name: ET_APM_SERVER_DEFAULT
          value: APM
        image: dynatrace/easytravel-headless-loadgen:latest
        name: easytravel-angular-loadgen
        resources:
          requests:
            memory: "500Mi"
          limits:
            memory: "500Mi"
