apiVersion: v1
kind: LimitRange
metadata:
  name: resource-limit-range
spec:
  limits:
  - default:
      cpu: "500m"
      memory: "500Mi"
    defaultRequest:
      cpu: "100m"
      memory: "256Mi"
    type: Container
